language: php

# Keep this up-to-date with the production environment
php: 
  - 7.0

sudo: false

before_install:
  - composer self-update

install: 
  - composer install --no-dev

# no tests for now
script: true
